# Site
name: 'The Cloud Dude'
description: 'Tech Blog'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'theclouddude'
email: 'theclouddudeinfo@gmail.com'
mailchimp-list: 'https://theclouddude.us10.list-manage.com/subscribe?u=964623620d6a167a844240f20&id=3b9dda24b6'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    theclouddude:
      name:           The Cloud Dude
      site:           http://www.theclouddude.com
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am the cloud dude. I hope you like my blogs!"
      email:          theclouddudeinfo@gmail.com
      twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
